update:
	docker run --rm --network liquibase-with-oracle_default -v /Users/seb/projects/liquibase-with-oracle/src/main/resources/changelog:/liquibase/changelog liquibase/liquibase --defaultsFile=/liquibase/changelog/liquibase.properties update

version:
	docker run --rm liquibase/liquibase --version
